# 基本概念

> zig作为一个新语言，文档十分稀缺，有些问题自己找不到，问ai也是胡编乱造，这里记录一些基本的概念

## 参数与解包的不可变性

> 在zig语言中，函数参数以及解包是默认不可变的，以`const`修饰

```zig

const std = @import("std");
const Info = struct { gender: bool, age: i8 };
pub fn main() !void {
    var my_info: ?Info = Info{ .gender = true, .age = 22 };
    // 修改一下成为变量，不然编译器不让过
    my_info.age = 24;
    _ = edit(info);
}
fn edit(info: Info) void {
    info.age = 23;
}
```

> 以上代码会报这样的错误

```
error: cannot assign to constant
        info.age = 23;`
        ~~~~^~~~
```

> 不能修改常量的值，与此类似的还有解包操作

```zig
 
const std = @import("std");
const Info = struct { gender: bool, age: i8 };
pub fn main() !void {
    var my_info: ?Info = Info{ .gender = true, .age = 22 };
    if (my_info) |info| {
        info.age = 23;
    }
    my_info.?.gender = false;
}
```

> 直接对解包的值修改也是不被允许的, 需要修改可以先使用`var`修饰符新建一个变量接收


## zig错误处理

> `zig`的返回值可以返回错误联合类型，类似`rust`的`Result`枚举，可以包含错误信息与返回值，函数如果可能返回错误则必须有错误处理操作

### 1. try

> 使用`try`关键字可以直接返回错误，类似`rust`的`?`操作符

```zig
pub fn main() !void {
   var res =  try func();
}

fn func() ![]u8 {
    // ...
}
```

> 如上代码，`func`函数可能返回错误，使用`try`直接抛出异常，res接收正常的返回值

### 2. catch

> 使用`catch`关键字捕获异常，并对异常进行处理

```zig
pub fn main() !void {
   var res1 =  func() catch |err| {
        return err;
    };
    var res2 = func() catch {
        return;
    };
}

fn func() ![]u8 {
    // ...
}
```

> 上述第一种写法其实作用与`try`相同， 如果不想解包错误可以直接`catch`加处理逻辑，当然如果逻辑只有一行，则花括号也可以省略如下

```zig
var res = func() catch return;
```

::: info
注意，如果将错误捕获到了闭包中，则不允许`_`忽略错误信息
:::

```zig[错误示范]

// 忽略解包错误，❌
var res1 = func() catch |_| {
    return
}; 
```

### 使用if else

> 分别处理成功与失败的逻辑，可以直接使用`if else`

```zig
if (func()) |val| {
    // ...
} else |err| {
    // 处理错误
}
```

### 不可恢复错误

> 与`go`,`rust`一致，`zig`也拥有不可恢复错误`panic`，通过`@panic()`内置函数来触发

```zig
@panic("不可恢复错误");
```

